"""added qsar model params.

Revision ID: 18751effe222
Revises: d777b6f63664
Create Date: 2022-12-12 13:03:56.253249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18751effe222'
down_revision = 'd777b6f63664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qsar_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_qsar_model_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qsar_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qsar_model_created'))
        batch_op.drop_column('created')

    # ### end Alembic commands ###
