"""removed prroperty class

Revision ID: 5f593f2b7733
Revises: e0d11edb6012
Create Date: 2022-12-09 12:44:26.138181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f593f2b7733'
down_revision = 'e0d11edb6012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compound_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_column('compound_id')
        batch_op.drop_column('activity')

    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_property')
    )
    # ### end Alembic commands ###
