"""updated tasks

Revision ID: 02e206275b0d
Revises: 223ba8fb8654
Create Date: 2022-12-21 09:05:31.753694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e206275b0d'
down_revision = '223ba8fb8654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_completed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('time_completed')
        batch_op.drop_column('time_submitted')

    # ### end Alembic commands ###
