"""added qsar model params.

Revision ID: 327f8e055e20
Revises: 18751effe222
Create Date: 2022-12-12 13:12:23.122786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327f8e055e20'
down_revision = '18751effe222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index('ix_dataset_created')

    with op.batch_alter_table('qsar_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_index('ix_qsar_model_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qsar_model', schema=None) as batch_op:
        batch_op.create_index('ix_qsar_model_created', ['created'], unique=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_created', ['created'], unique=False)

    # ### end Alembic commands ###
