"""added qsar model.

Revision ID: d777b6f63664
Revises: 5f593f2b7733
Create Date: 2022-12-12 12:42:24.838125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd777b6f63664'
down_revision = '5f593f2b7733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qsar_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('descriptors', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('sklearn_model', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name='dataset-chemical'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user-dataset'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qsar_model'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qsar_model')
    # ### end Alembic commands ###
